apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: globo-paths
  namespace: globomantics
spec:
  ingressClassName: traefik
  rules:
  - host: shop.globo.com
    http:
      paths:
      - path: /catalog
        pathType: Prefix
        backend:
          service:
            name: catalog
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: api
            port:
              number: 80
