apiVersion: apps/v1
kind: Deployment
metadata:
  name: globo-frontend
  namespace: globomantics
  labels:
    app: globo-frontend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: globo-frontend
  template:
    metadata:
      labels:
        app: globo-frontend
    spec:
      containers:
        - name: nginx
          image: nginx:1.24
          ports:
            - containerPort: 80
