apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: distroless-data
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: distroless-pod
spec:
  restartPolicy: Always
  securityContext:
    runAsNonRoot: true
    runAsUser: 65532
    fsGroup: 65532
  containers:
    - name: app
      image: dbclinton/hits:v1
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop: ["ALL"]
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: distroless-data
