apiVersion: v1
kind: Pod
metadata:
  name: globo-toobig
  namespace: globomantics
spec:
  containers:
    - name: globo-toobig
      image: nginx:1.31
      resources:
        requests:
          memory: 2Gi
        limits:
          memory: 2Gi
