apiVersion: v1
kind: Pod
metadata:
  name: globo-catalog-ssd
  namespace: globomantics
  labels:
    app: globo-catalog-ssd
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: disktype
                operator: In
                values: ["ssd"]
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 50
          preference:
            matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values: ["us-east-1a"]
  containers:
    - name: catalog
      image: nginx:1.31
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
